name: Build LLVM SYCL (Linux)

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  SCCACHE_DIR: ${{ github.workspace }}/sccache
  SCCACHE_CACHE_SIZE: 1G
  X: 12
  Y: 9
  Z: 1

jobs:
  linux-hip:
    runs-on: ubuntu-24.04
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/cache@v5
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: sccache-${{ runner.os }}-

      - name: Install packages
        run: |
          sudo mkdir --parents --mode=0755 /etc/apt/keyrings
          wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
          sudo tee /etc/apt/sources.list.d/rocm.list << EOF
          deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/latest noble main
          deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/graphics/latest/ubuntu noble main
          EOF
          sudo tee /etc/apt/preferences.d/rocm-pin-600 << EOF
          Package: *
          Pin: release o=repo.radeon.com
          Pin-Priority: 600
          EOF

          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb

          sudo apt-get update
          sudo apt-get -y install sccache ninja-build rocm-hip-runtime-dev \
            cuda-minimal-build-${{ env.X }}-${{ env.Y }} \
            cuda-cupti-dev-${{ env.X }}-${{ env.Y }} \
            cuda-nvml-dev-${{ env.X }}-${{ env.Y }}

      - name: Checkout LLVM
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh api repos/intel/llvm/releases/latest --jq '.tag_name')
          echo "Cloning intel/llvm at tag: $tag"
          git clone --config core.autocrlf=false --depth 1 https://github.com/intel/llvm -b $tag

      - name: Configure LLVM
        env:
          CC: clang-18
          CXX: clang++-18
          CUDA_LIB_PATH: /usr/local/cuda/lib64/stubs
        run: |
          python llvm/buildbot/configure.py --hip --cuda --native_cpu \
            -DLLVM_SPIRV_ENABLE_LIBSPIRV_DIS=off -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            --disable-jit --no-assertions --add_security_flags=sanitize \
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache \
            -DLLVM_INSTALL_UTILS=ON \
            -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=SPIRV

      - name: Build LLVM
        run: |
          sccache --start-server
          python llvm/buildbot/compile.py
          sccache --show-stats
          LD_LIBRARY_PATH=${{ github.workspace }}/llvm/build/install/lib llvm/build/install/bin/sycl-ls --verbose

      - uses: actions/upload-artifact@v7
        with:
          name: llvm
          path: llvm/build/install
